markdown: redcarpet
permalink: /:categories/:title.html
url:
lsi: false
pygments: true
safe: true
auto: false

paginate: 8
paginate_path: "page:num"

# presonal config
domain: mycolor.github.io
title: Zhaofn
description: 一起来讨论技术吧！
author: Zhaofn
email: zhaofn123@sina.com
github: mycolor

config:
  js_dir:
  img_dir:
  css_dir:
