markdown: redcarpet
permalink: /:categories/:title.html
url:
lsi: false
pygments: true
safe: true
auto: false

paginate: 8
paginate_path: "page:num"

# presonal config
domain: blog.zbc7.com
title: zbc's Blog
description: Android, Cocos2d, Java Web, Linux, reading...
author: zbc
email: zbc0512@163.com
github: zbcblog

config:
  js_dir:
  img_dir:
  css_dir:
